CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  is_admin boolean NOT NULL DEFAULT false,
  is_superuser boolean NOT NULL DEFAULT false,
  email_verified boolean NOT NULL DEFAULT false,
  email_verification_token_hash text,
  email_verification_expires_at timestamp without time zone,
  email_verification_sent_at timestamp without time zone,
  password_reset_token_hash text,
  password_reset_expires_at timestamp without time zone,
  leaderboard_hidden boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS problems (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  statement_latex text NOT NULL,
  solution_latex text,
  problem_source text,
  proposed_by text,
  problem_type text NOT NULL,
  is_current boolean NOT NULL DEFAULT false,
  is_archived boolean NOT NULL DEFAULT false,
  release_date date,
  release_at timestamp with time zone,
  due_date date,
  due_at timestamp with time zone,
  hints text,
  hints_enabled boolean NOT NULL DEFAULT true,
  allow_hint_requests boolean NOT NULL DEFAULT true,
  difficulty_rating integer CHECK (difficulty_rating BETWEEN 1 AND 10)
);

CREATE TABLE IF NOT EXISTS submissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  problem_id integer NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
  answer_text text,
  work_text text,
  file_name text,
  file_type text,
  file_data bytea,
  is_correct boolean,
  score integer NOT NULL DEFAULT 0 CHECK (score >= 0),
  feedback text,
  graded_by integer REFERENCES users(id) ON DELETE SET NULL,
  graded_at timestamp without time zone,
  submitted_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (answer_text IS NOT NULL OR work_text IS NOT NULL OR file_data IS NOT NULL),
  CHECK (score BETWEEN 0 AND 5)
);

CREATE TABLE IF NOT EXISTS seasons (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS problem_proposals (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title text NOT NULL,
  statement_latex text NOT NULL,
  solution_latex text,
  source text,
  notes text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hint_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  problem_id integer NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
  message text,
  response text,
  responded_at timestamp without time zone,
  responded_by integer REFERENCES users(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- These additions make this migration safe for the partial tables from the original project.
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS answer_text text;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS work_text text;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS file_name text;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS file_type text;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS file_data bytea;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS is_correct boolean;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS score integer NOT NULL DEFAULT 0;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS feedback text;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS graded_by integer REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS graded_at timestamp without time zone;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS submitted_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS problems_current_idx ON problems (is_current, problem_type);
CREATE INDEX IF NOT EXISTS problems_archive_idx ON problems (is_archived, release_date DESC);
CREATE INDEX IF NOT EXISTS submissions_user_idx ON submissions (user_id, submitted_at DESC);
CREATE INDEX IF NOT EXISTS submissions_problem_idx ON submissions (problem_id);
CREATE INDEX IF NOT EXISTS proposals_status_idx ON problem_proposals (status, created_at DESC);
CREATE INDEX IF NOT EXISTS hint_requests_status_idx ON hint_requests (status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_verification_token_idx ON users (email_verification_token_hash) WHERE email_verification_token_hash IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS users_password_reset_token_idx ON users (password_reset_token_hash) WHERE password_reset_token_hash IS NOT NULL;
