ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_superuser boolean NOT NULL DEFAULT false;

ALTER TABLE problems DROP CONSTRAINT IF EXISTS problems_difficulty_rating_check;
ALTER TABLE problems ADD CONSTRAINT problems_difficulty_rating_check CHECK (difficulty_rating BETWEEN 1 AND 10);

ALTER TABLE submissions ADD COLUMN IF NOT EXISTS graded_by integer REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS graded_at timestamp without time zone;
UPDATE submissions SET score = LEAST(GREATEST(score, 0), 5);
UPDATE submissions SET graded_at = submitted_at WHERE graded_at IS NULL AND is_correct IS NOT NULL;

CREATE TABLE IF NOT EXISTS seasons (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS problem_proposals (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title text NOT NULL,
  statement_latex text NOT NULL,
  solution_latex text,
  source text,
  notes text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hint_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  problem_id integer NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
  message text,
  response text,
  responded_at timestamp without time zone,
  responded_by integer REFERENCES users(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS proposals_status_idx ON problem_proposals (status, created_at DESC);
CREATE INDEX IF NOT EXISTS hint_requests_status_idx ON hint_requests (status, created_at DESC);

INSERT INTO seasons (name, start_date, end_date, is_active)
VALUES ('Fall 2026', CURRENT_DATE, DATE '2026-12-31', true)
ON CONFLICT (name) DO UPDATE
SET start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    is_active = EXCLUDED.is_active;
