CREATE TABLE IF NOT EXISTS login_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES users(id) ON DELETE SET NULL,
  username text NOT NULL,
  email text NOT NULL,
  logged_in_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_visits (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path text NOT NULL,
  visited_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS login_events_logged_in_at_idx ON login_events (logged_in_at DESC);
CREATE INDEX IF NOT EXISTS site_visits_visited_at_idx ON site_visits (visited_at DESC);
